apiVersion: apps/v1
kind: Deployment
metadata: 
  name: django-dep
spec:
  replicas: 5
  selector:
    matchLabels:
      app: django
  template:
    metadata:
      labels: 
        app: django
    spec:
      containers:
      - name: django-container
        image: akashjyothi/django-ecom:latest 
        ports:
        - containerPort: 8000
              
